In [6]:
import tushare as ts
ts.set_token('854634d420c0b6aea2907030279da881519909692cf56e6f35c4718c')
# #  初始化pro接口
pro = ts.pro_api()
import pandas as pd

In [14]:
df = pd.read_parquet('data/trade/stock/20230928.parquet')

In [15]:
df

,code,high_x,low_x,open_x,close,pre_close_x,change_x,vol_x,amount_x,date,...,ocf_yoy,roe_yoy,bps_yoy,assets_yoy,eqt_yoy,tr_yoy,or_yoy,q_sales_yoy,q_op_qoq,equity_yoy
0,301558,21.50,18.88,20.20,18.95,7.33,158.53,862049.0,1.735256e+09,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,300968,10.79,9.07,9.08,10.79,8.99,20.02,402965.0,4.175962e+08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,300545,29.38,24.55,24.55,29.38,24.48,20.02,205077.0,5.673591e+08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,301225,40.57,33.89,33.89,40.57,33.81,19.99,122316.0,4.825028e+08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,300322,9.44,7.91,7.91,9.44,7.87,19.95,581881.0,5.161318e+08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5276,688320,44.29,39.93,44.10,40.00,44.10,-9.30,97927.0,4.080489e+08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5277,603895,26.26,26.26,26.26,26.26,29.18,-10.01,23160.0,6.081816e+07,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5278,002691,9.08,7.54,8.73,7.54,8.38,-10.02,758287.0,6.250465e+08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5279,002406,8.12,7.62,8.00,7.62,8.47,-10.04,1707257.0,1.315300e+09,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5280,301520,83.38,74.60,82.78,75.02,88.00,-14.75,93271.0,7.262790e+08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.rename(columns={"close_x":"close"}, inplace=True)

In [13]:
df.to_parquet('data/trade/stock/20230928.parquet')

In [5]:
pro.fina_indicator_vip()

Exception: 抱歉，您没有访问该接口的权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。